version: '1.0.0'

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: chat_app
      MYSQL_USER: Noa
      MYSQL_PASSWORD: noa@2021