CREATE DATABASE IF NOT EXSIT chat_app;

use chat_app
CREATE TABLE IF NOT EXIST users(
    ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXSIT rooms(
    ID int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name_room VARCHAR(255) NOT NULL
);